### ISSUE TITLE
Start on basic functionality of graph engine

### ISSUE THREAD

**Issue by xavcochran** [HelixDB/helix-db#5]
Basic functionality includes:
- Creating nodes
- Creating edges between nodes
- Get a node
- Get an edge
- Basic traversals

**Comment by xav-db** [comment]
Okay the initial graph db is pretty much done. You can do node to edge, edge to node, node to node, queries by label, multiple jumps etc. There is A LOT of room for performance improvement as ive been focusing mostly getting something that works well without worrying about complicating it. 

Current traversal steps implemented are: v, e, add_v, add_e, out, out_e, in, in_e. All of the traversals via an edge can take a label to refine the traversal. 

My approach so far has been to have a traversal builder that builds up the traversal as you go (a bit like gremlin) getting and refining the data at each step. I tested a complex unoptimised query on a graph of 100,000 nodes where each node has 10 outgoing edges (1,000,000 total) and the traversal took about 30ms (it takes 60µs with 3 nodes and 3 edge) which isn’t bad given the point we are at with no caching, optimisations or parallelism.
